### ISSUE TITLE
ask for document title

### ISSUE THREAD

**Issue by beber-msft** [clusterzx/paperless-ai#4]
Hello,
does this only do tagging and correspondent or can it also do document title?

**Comment by clusterzx** [comment]
It also does the title.

**Comment by beber-msft** [comment]
thanks, this is great.
looking at it now in more detail.
two more qq.
a) setup seems to not always failback to GPT4.5T and not accepting my switch to 4o-mini.
b) is there a way to have it look only at inbox tagged items?

**Comment by clusterzx** [comment]
Thank you for your questions:

A) I will look this issue up and try to reproduce it.
B) Currently it looks for all documents that are not already processed by paperless-ai. Though it might be a neat feature request for upcoming versions to declare which documents gonna be processed.

**Comment by clusterzx** [comment]
I can't reproduce the issue with fallback to a different OpenAI Model. Also the setup process does not include GPT4 Turbo. 
Please verify something for me:

1. Do a fresh install process of paperless-ai
2. Select for example GTP-4o-mini
3. Finish the installation
4. Look into the created .env file and verify what model is saved there

Then please get back here and tell me your findings.

**Comment by clusterzx** [comment]
Yeah regarding the switch back is because if you reload or reopen the setup process it will alway preselect the first entry from the drop down. So its just a visual thing. 

I assume I can close the issue here?

**Comment by beber-msft** [comment]
appreciate your work and help!

**Comment by clusterzx** [comment]
I will tag you here in the next days when the new feature is implemented.
You are most welcome 👍

**Comment by clusterzx** [comment]
Done! You can now predefine in the setup process wich pretagged documents will be processed.
