### ISSUE TITLE
Programm not starting

### ISSUE THREAD

**Issue by MephistoJB** [clusterzx/paperless-ai#5]
Hi there. Trying to get this running.

Using Ollama. the urls should be fine. getting this error in the log
ollama running on the same server running together with paperless and your app.

Paperless URL: http://server:8000/api
Ollama URL: http://server:11434

Server running on port 3000
Running initial scan...
Starting document scan...
Error during document scan: TypeError: Cannot read properties of undefined (reading 'length')
    at scanDocuments (/app/server.js:48:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-12-27T20:41:12: PM2 log: [PM2][WORKER] Reset the restart delay, as app paperless-assistant has been up for more than 30000ms

When looking into the server.js I see this is the first command after setup-check and the retrieval of the taglist is not working. Could you give me a hint here please.

Thank you :)

**Comment by clusterzx** [comment]
The error seems to be the issue of not finding or getting a valid response back from the /api/tags route.
Do you have any tags already in your paperless-ngx instance? Or maybe there is an issue with the user rights to access this specific api route?

**Comment by MephistoJB** [comment]
I used the superuser account so that should not be a problem. And yes I have a lot of tags. about 30 or so. Any other ideas?

**Comment by clusterzx** [comment]
I did a test with a fresh instance  of paperless-ngx and fresh paperless-ai instance and have no issues here in my site. 

I will write you a little debug script so you can test the endpoint. 

What OS is the paperless-ai running on?

**Comment by MephistoJB** [comment]
Sounds great. Thanks you. I run Both on unraid as Docker

**Comment by clusterzx** [comment]
https://github.com/clusterzx/paperless-ai/blob/main/README.md#debug-interface

Please remove the running docker container and delete the old docker image. Pull the new one and test the new debug route documented in the README.

**Comment by MephistoJB** [comment]
Did you change anything? Same config. But now it worked everything

**Comment by clusterzx** [comment]
No I only added the part with the debug page.
Can you access the debug page and do some testes there?

**Comment by MephistoJB** [comment]
I needed to shut it down as it ran on Autopilot instantly. I Need to Test this more before I can let this Happen. Is there a way to let it run only on manual Mode?

**Comment by clusterzx** [comment]
No not now but it would be a good next feature. Gonna take that into the roadmap. 

Can I close the issue here?

**Comment by MephistoJB** [comment]
Yes but I have an offer for you. Maybe you can have a Look into here. There is a project I contributed to and it would be awesome if we could combine both projects. https://github.com/jgillula/paperless-ngx-postprocessor  It looks like this project does exactly what you have on your todo list right now. If you are interested I would be happy to help.

**Comment by clusterzx** [comment]
As I can see you already converted the logic to python and made a PR there. 

Good work! But I don't see the benefit to combine those two projects as you already did the AI integration there. 

My approach is only AI based and should be almost to zero config and autonomous. 

I am happy that you liked my approach and integrate that into other useful repositories. 

Closed for now
